name: distillation_v2vnet
root_dir: '/home/hcz/HCZ/v2x-vit/v2xset/train'
validate_dir: '/home/hcz/HCZ/v2x-vit/v2xset/validate'

wild_setting:
  async: false
  async_mode: 'sim'
  async_overhead: 100
  seed: 25
  loc_err: false
  xyz_std: 0.2
  ryp_std: 0.2
  data_size: 1.06 # Mb!!
  transmission_speed: 27 # Mbps!!
  backbone_delay: 10 # ms

yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 4
  epoches: 60
  eval_freq: 1
  save_freq: 1
  max_cav: &max_cav 5

fusion:
  core_method: 'IntermediateFusionDataset' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args:
    cur_ego_pose_flag: True
      # when the cur_ego_pose_flag is set to True, there is no time gap
      # between  the time when the LiDAR data is captured by connected
      # agents and when the extracted features are received by
      # the ego vehicle, which is equal to implement STCM. When set to False,
      # STCM has to be used.


# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  # lidar range for each individual cav.
  cav_lidar_range: &cav_lidar [-140.8, -38.4, -3 , 140.8, 38.4, 1]

#45度

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

#  - NAME: random_world_rotation
#    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

#  - NAME: random_world_scaling
#    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]


# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar

    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 4
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.27
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

teacher_model:
  core_method: pillarNet_teacher
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    pillarNet_teacher:
      num_features: 64
      grid_size: [704,192,1]

    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 2 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384 # 128 * 3
    cls_head_dim: 256
    anchor_num: *achor_num

# model related
model:
  core_method: pillarNet_distillation_v2vnet
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 32 # compression rate
    backbone_fix: false

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    pillarNet_student:
      num_features: 64

    shrink_header:
      kernal_size: [3]
      stride: [2]
      padding: [1]
      dim: [256]
      input_dim: 384 # 128 * 3

    v2vfusion:
      use_temporal_encoding: false
      voxel_size: *voxel_size
      downsample_rate: 4
      num_iteration: 2
      in_channels: 256
      gru_flag: True
      agg_operator: "avg" # max or avg
      conv_gru:
        H: 48
        W: 176
        num_layers: 1
        kernel_size: [[3,3]]

combine_loss:
  core_method: combine_loss
  args:
    cls_weight: 1.0
    reg: 2.0
loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0


optimizer:
  core_method: Adam
  lr: 0.001
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: step #step, multistep and Exponential support
  gamma: 0.1
  step_size: 20

